name: Test boolean input

on:
  workflow_dispatch:
    inputs:
      run_migration:
        type: boolean
        default: true

jobs:
  test:
    name: test
    runs-on: [ ubuntu-latest ]
    steps:
      - run: echo Start
      - name: step 1
        if: github.event.inputs.run_migration == true
        run: |
          echo "pre migration step" 

      - name: step 2
        if: github.event.inputs.run_migration == true
        run: |
          echo "migration step"

      - name: step 3
        if: github.event.inputs.run_migration == true
        run: |
          echo "post migration step"
      - run: echo End
