name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a common build"
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: PRODUCTION
    steps:
      - run: echo "This is a production deploy"
